[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "devopslab5"
version = "0.0.1"
description = "My DevOps Lab 5 App on GitHub"
dependencies = ["flask"]

[tool.setuptools]
py-modules = ["app"]